server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:rating
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


